export const SIZES = ["S", "M", "L", "XL", "XXL", "XXXL"];

export const WOMENS_DETAILS = [
  {
    name: "women kurtis",
    src: "https://static.wixstatic.com/media/1b75b0_07802a8a12c341da8bd39c382988cbd5~mv2.jpg/v1/fill/w_560,h_700,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/1b75b0_07802a8a12c341da8bd39c382988cbd5~mv2.jpg",
    type: "umberella type chudithar",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "860",
    delivery: "Free delivery",
    stockCount: 60,

    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://i.pinimg.com/originals/e2/db/0f/e2db0f061923b852c6ba6f976c35edd1.jpg",
    type: "embroid design kurtis",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    delivery: "Free delivery",
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://content3.jdmagicbox.com/comp/tiruvarur/x5/9999p4366.4366.161101162749.l5x5/catalogue/chudithar-park-thiruthuraipoondi-tiruvarur-ujx6j.jpg",
    type: "rounded bottom design",
    colors: ["pink", "green", "blue", "orange", "red", ],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    delivery: "delivery ₹30",
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZMe9hiUk9elh8I3lb1rD58RO74lCq8-12uA&usqp=CAU",
    type: "cotton frog modal",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    delivery: "Free delivery",
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://i.pinimg.com/236x/50/e7/3b/50e73bc51536a18e6c6853e2117bb646.jpg",
    type: "Women Rayon Flared Kurti",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    delivery: "delivery ₹30",
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://images.meesho.com/images/products/192128707/lsk64_512.webp",
    type: "Silk Anarkali Festive Kurti ",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    delivery: "Free delivery",
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://images.meesho.com/images/products/218913151/g23ii_512.webp",
    type: "Women's Mustard Cotton Floral Print",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    delivery: "Free delivery",
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://mahezon.in/cdn/shop/files/IMG-20230922-WA0019_800x1026_crop_center@2x.jpg?v=1698067564",
    type: "Mandarin Collar Printed Kurta",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    delivery: "delivery ₹30",
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://i.pinimg.com/736x/68/3d/c8/683dc8bb0d4282b9af5fe04881a8d6fb.jpg",
    type: "Women Rayon Anarkali Kurti",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    delivery: "Free delivery",
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://assets0.mirraw.com/images/11749697/image_zoom.jpeg?1691999814",
    type: "Women Straight Kurti",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    delivery: "Free delivery",
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC08KdaelTposKdVRdOeRThUN1l8Gg8MYulw&usqp=CAU",
    type: "Women's Yellow Cotton A-Line Kurta",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    delivery: "Delivery ₹30",
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://www.joshindia.com/cdn/shop/products/V3-277-5.jpg?v=1680944502&width=1445",
    type: "Cotton Calf Length Anarkali Kurti",
    colors: ["pink", "orange", "blue", "skyblue", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    delivery: "Free delivery",
    shop: "@2B Boutique",
  },
];

export const COLORS_WITH_EXCODES = {
  blue: "#0000FF",
  orange: "#FFA500",
  yellow: "#FFD400",
  green: "#A1DFA2",
  deeppink: "#D60178",
  hotpink: "#E76FB3",
  royalblue: "#162453",
  lightblue: "#5A9FD8",
  skyblue: "#9FD9FE",
  lightgreen: "#598061",
  pink: "#F70062",
  brown: "#541513",
  darkbrown: "#3E1213",
  lightbrown: "#BA7D5F",
  grey: "#909090",
  gray: "#636363",
  black: "#000000",
  red: "#FF0000",
  darkblue: "#223BC9",
  palepink: "#E57D90",
};
