export const KIDS_DETAILS = [
  {
    stockId: 1,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://i.pinimg.com/736x/cb/79/0e/cb790e62bbccc24aafbfcfe9997fba4a.jpg",
    type: "Multi Color Frog",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 2,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaId4zJRc9cMPmKW4Q-pgUwYKAhCO_dPFmetu3EYcVsrAQHwI-7vCRWqZML3nIVOlA_e0&usqp=CAU",
    type: "Violet color frog",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 800,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 3,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://5.imimg.com/data5/SELLER/Default/2021/3/AA/PZ/GH/45535844/kids-ethnic-wear-500x500.jpg",
    type: "Girl Kids green ethnic wear ",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 999,
    deliveryCharge: 20,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 4,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://5.imimg.com/data5/ANDROID/Default/2022/6/YY/YY/JQ/26434468/product-jpeg.jpg",
    type: "Cotton yellow and pista green dress",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 5,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://i.pinimg.com/736x/0c/cd/f5/0ccdf574663f0bde7bcd1f59b15a7d3a.jpg",
    type: "kids designer dress",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 1200,
    deliveryCharge: 30,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 6,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmE8ntb_ShWgY6UleYWGTd6WQDI2TUQEtXYg&usqp=CAU",
    type: "Green and yellow ethnic wear",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 7,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrJ-skm-Y1RWpB9iSLlLsh85tIqxMA-kapbMtWwXCPNTJFmIeeRpxC9vXwhRu8NdXvm4Y&usqp=CAU",
    type: "Boy baby dress with cap",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 1350,
    deliveryCharge: 35,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 8,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRJXvJt9cLRbsFVuOVLBomS8Tx2_XGHDgD_gk1DcUp9gKyZSOvV-G_w82-tFId5eHiyZk&usqp=CAU",
    type: "Boy baby occasion outfit",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 9,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://fancydressnoida.com/wp-content/uploads/2022/04/IMG_8885-a-683x1024.webp",
    type: "Folk dance dress",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 899,
    deliveryCharge: 10,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 10,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://i.etsystatic.com/24622444/r/il/39827d/4389494521/il_1080xN.4389494521_a7di.jpg",
    type: "Boy kurta pajama dress",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 550,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 11,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://i.pinimg.com/236x/84/78/17/847817868b648db4befafa56139ebd69.jpg",
    type: "boys wedding outfit",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 1500,
    deliveryCharge: 40,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 12,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://i.etsystatic.com/24622444/r/il/4abe8e/4016612277/il_570xN.4016612277_ldvz.jpg",
    type: "Boy Traditional oufit",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 13,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP-UavvJ35Oxqi2hR2gDZGhKR0VqCyG14Zvw&usqp=CAU",
    type: " Cool blue and white dress",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 14,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-sRk3DFh6vryEFB7wd9CiO5UGC3qRJdJmFf0ADA2zpuViveDtfOOtxorLC9SU3BS7fjc&usqp=CAU",
    type: "Boy baby dress",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 15,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSda-kWSDY80gS58G3NUrqMArpzrSPXEYrN9JnFGjmXmG4N-YnpW7D5wJcbcp2eWAS5PZc&usqp=CAU",
    type: "Dark grey jean shirt for kids",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 16,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://www.tradeinn.com/f/13960/139600488/garcia-b35630-long-sleeve-shirt.jpg",
    type: "Boy baby dress ",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 17,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://www.next.co.uk/nxtcms/resource/image/4806358/portrait_ratio1x1/305/305/52a5866458bfb60ff863eec44bfaeb1/83763CB7F22F1E84412E5E0632037EA2/boys.jpg",
    type: "Children clothes and shoes",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 18,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://p.kindpng.com/picc/s/733-7333530_child-model-fashion-show-kids-boy-fashion-model.png",
    type: "Transparent kids dress",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 19,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDV6M0XWU2txH9_bGnQjb0Bbd14W5-XBrCS6lPHMKMujZ_colpEUGaD8FCUCWZ_mZeDj4&usqp=CAU",
    type: "7 years baby dress",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 20,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://m.media-amazon.com/images/I/71yQHr9wMgL.jpg",
    type: "Red grey kids wear",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 21,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRz1l_U8mztUlqe16UvpGZemiJexD-8Rt8fPA&usqp=CAU",
    type: "Baby girl lehenga choli",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 22,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVV3f0xpHvIQ-fdXzryDc5Zuq4TY8F_g4O9Q&usqp=CAU",
    type: "Traditional lehenga choli",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 23,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://m.media-amazon.com/images/I/91OUxBrQRlL._SX569_.jpg",
    type: "Pattu paavadai",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 24,
    category: "kids",
    name: "Kids Shirt and Frog",
    src: "https://m.media-amazon.com/images/I/81AsKulSWeL._AC_UY1100_.jpg",
    type: "paavadai sattai",
    colors: ["blue", "grey", "skyblue", "black"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
];
