export const MENS_DETAILS = [
  {
    stockId: 1,
    category: "mens",
    name: "Mens shirt",
    src: "https://toppng.com/uploads/preview/mens-fashion-png-image-mens-wear-11563641203cmrdzizcrd.png",
    type: "casual  shirt",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens shirt",
    src: "https://img.freepik.com/free-photo/young-handsome-hipster-man-trendy-style-outfit-denim-shirt-trousers-sunglasses-hat-isolated-jumping-cheerful-pointing-finger_285396-1517.jpg?size=626&ext=jpg&ga=GA1.1.2091009926.1696475451&semt=ais",
    type: "formal shirt",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens shirt",
    src: "https://img.freepik.com/free-photo/man-portrait_1296-626.jpg?size=626&ext=jpg&ga=GA1.1.2091009926.1696475451&semt=ais",
    type: "casual shirt",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens shirt",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQg_rT4xeJLsz0DGf6s8y8D2OacS4w8vxJmIw&usqp=CAU",
    type: "formal shirt",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens shirt",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3iOX4vjfOSZYpY6mJLATfL-7tyM8ro80HQg&usqp=CAU",
    type: "casual shirt",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens shirt",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7GUh25vnAW_4ghF1IbPQDsYXcHyWK68EOCQ&usqp=CAU",
    type: "formal shirt",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens shirt",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJC7a-nS0osq8CfwcxZC0CqGXQ6ubBFgfOJw&usqp=CAU",
    type: "formal shirt",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens jeans",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyFXHJQEkM5kOSX7hhrZKeuf7Wnpna4KOC-jqRuwsoJ_FqeqomIMD42bcYelnTeqCL9yg&usqp=CAU",
    type: "super skinny fit",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens jeans",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCyxEXhH6Tn3ndPIa19sZLa5vJU9hrGSse26WF3li80qa_8UrYNGXv0dxTtD5TzKUbokI&usqp=CAU",
    type: "Skinny fit",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens jeans",
    src: "https://media.istockphoto.com/id/527236518/photo/mans-legs.jpg?s=612x612&w=0&k=20&c=lczyG0ZkWelpn_o-I_VpjAMo_sA3WpdWHMlgZjCSE-k=",
    type: "fashion jeans",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens jeans",
    src: "https://rukminim1.flixcart.com/image/850/1000/xif0q/jean/a/y/a/-original-imagcapdtcyxh6aj-bb.jpeg?q=20",
    type: "Slim fit",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens jeans",
    src: "https://rukminim2.flixcart.com/image/850/1000/xif0q/jean/r/b/e/36-men-s-jeans-turkey-imported-original-imagmhh5tnnhce8f.jpeg?q=20",
    type: "torkey imported blue jean",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens jeans",
    src: "https://assets.myntassets.com/dpr_1.5,q_60,w_400,c_limit,fl_progressive/assets/images/16047022/2021/11/10/4af4fdf5-bc0d-4ace-9170-6ef30f9e97e31636525511211JohnPrideMenGreyHeavyFadeStretchableJeans1.jpg",
    type: " Regular Fit Stretchable Cotton Jeans",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens jeans",
    src: "https://www.trigger.in/cdn/shop/products/0W2A6094.jpg?v=1673518256",
    type: "Royal blue denim jeans",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens jeans",
    src: "https://c.bflcdn.com/t_pm/f_auto,q_auto/products/23/12/196122180901_BTM_1.JPG",
    type: "straight fit denim blue",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens jeans",
    src: "https://www.sportsdirect.com/images/products/68424918_h.jpg",
    type: "casual & fashionable jeans",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens T-shirt",
    src: "https://4.imimg.com/data4/AA/HC/MY-26596027/men-s-fancy-t-shirt.jpg",
    type: "Mens fancy t-shirt",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens T-shirt",
    src: "https://images-na.ssl-images-amazon.com/images/I/61-jBuhtgZL._UL1500_.jpg",
    type: "casual t-shirt",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens T-shirt",
    src: "https://www.myshopstore.in/wp-content/uploads/2021/08/100-Cotton-Regular-Fit-Polo-Neck-Full-Sleeve-Mens-T-Shirt-A.jpg",
    type: "full neck sleeve",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens T-shirt",
    src: "https://5.imimg.com/data5/KT/DY/SH/ANDROID-106477818/ms-1-512-3260982-jpg.jpg",
    type: "Full sleeve mens t-shirt",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens T-shirt",
    src: "https://www.jiomart.com/images/product/original/rvx8lkd05o/lewel-men-s-hooded-stylish-checkered-full-sleeve-t-shirt-product-images-rvx8lkd05o-0-202212151421.jpg?im=Resize=(500,630)",
    type: "stylish checkered full sleeve",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens T-shirt",
    src: "https://rukminim2.flixcart.com/image/850/1000/xif0q/t-shirt/q/s/g/s-t14-t2-autna-original-imagqnchhwzgwuzw.jpeg?q=90",
    type: "round neck full sleeve",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens T-shirt",
    src: "https://rukminim1.flixcart.com/image/850/850/xif0q/shopsy-t-shirt/7/h/1/l-blk-all-lining-full-l-2-ruggstar-original-imagh2gz5zkxyy6s.jpeg?q=90",
    type: "black mens full sleeve",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
  {
    stockId: 1,
    category: "mens",
    name: "Mens t-shirt",
    src: "https://i.pinimg.com/236x/ab/d1/c1/abd1c1c50981a7dd553d9b59ddf0a727.jpg",
    type: "full sleeve t-shirt",
    colors: ["blue", "grey", "skyblue", "black", "lightblue"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: 750,
    deliveryCharge: 0,
    quantity: 30,
    cost: 2000,
    date: "10-jan-2023",
    shop: "@2B Boutique",
  },
];
