export const SIZES = ["S", "M", "L", "XL", "XXL", "XXXL"];

export const WOMENS_DETAILS = [
  {
    name: "women kurtis",
    src: "https://static-01.daraz.com.bd/p/09cefe96d56ee10706714dadf29e2e46.jpg",
    type: "umberella type chudithar",
    // colors: ["pink", "green", "blue", "orange", "red"],
    colors: ["pink", "green"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "860",
    deliveryCharge: 0,
    stockCount: 60,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://m.media-amazon.com/images/I/71nRvksEuGL._SX466_.jpg",
    type: "embroid design kurtis",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "850",
    stockCount: 60,
    deliveryCharge: 10,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://rukminim2.flixcart.com/image/850/1000/jv44mfk0/dress/r/q/r/xl-11-kurti-studio-original-imafg3mppcapk2gc.jpeg?q=20&crop=false",
    type: "rounded bottom design",
    // colors: ["pink", "green", "blue", "orange", "red"],
    colors: ["pink"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "899",
    stockCount: 60,
    deliveryCharge: 15,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://m.media-amazon.com/images/I/71dSMjhXCnS._SY550_.jpg",
    type: "cotton frog modal",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "950",
    stockCount: 60,
    deliveryCharge: 20,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://assets.ajio.com/medias/sys_master/root/20230928/Vzgs/65148188ddf77915190b1e80/-473Wx593H-466250538-lavender-MODEL.jpg",
    type: "Women Rayon Flared Kurti",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    deliveryCharge: 0,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://i.pinimg.com/736x/31/65/9d/31659d612e2e56692b3df39b007bf632.jpg",
    type: "Silk Anarkali Festive Kurti ",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "1100",
    stockCount: 60,
    deliveryCharge: 25,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://images.wholesalesalwar.com/2022y/December/37281/Red-Rayon-Viscose-Casual-Wear-Fancy-Kurti-ZCK31-2.jpg",
    type: "Women's Mustard Cotton Floral Print",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    deliveryCharge: 0,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://ladyindia.com/cdn/shop/products/717ZLSI9-bL._UL1500_1024x1024.jpg?v=1571439194",
    type: "Mandarin Collar Printed Kurta",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "1200",
    stockCount: 60,
    deliveryCharge: 30,
    shop: "@2B Boutique",
  },

  //################################################
  {
    name: "women kurtis",
    src: "https://static.wixstatic.com/media/1b75b0_07802a8a12c341da8bd39c382988cbd5~mv2.jpg/v1/fill/w_560,h_700,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/1b75b0_07802a8a12c341da8bd39c382988cbd5~mv2.jpg",
    type: "umberella type chudithar",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "860",
    deliveryCharge: 0,
    stockCount: 60,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://rukminim2.flixcart.com/image/850/1000/xif0q/kurta/y/y/2/xl-tsik-17-pyaritrends-original-imagpvbzetza4zg2.jpeg?q=90&crop=false",
    type: "embroid design kurtis",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "850",
    stockCount: 60,
    deliveryCharge: 10,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://m.media-amazon.com/images/I/81I9iB+EAjL._AC_UY1100_.jpg",
    type: "rounded bottom design",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "899",
    stockCount: 60,
    deliveryCharge: 15,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://im.idiva.com/content/2023/Jan/Pattern-Kurti-Design-18_63d8b59e85d98.jpg",
    type: "cotton frog modal",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "950",
    stockCount: 60,
    deliveryCharge: 20,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://images.meesho.com/images/products/41026029/dujpd_512.jpg",
    type: "Women Rayon Flared Kurti",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    deliveryCharge: 0,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://m.media-amazon.com/images/I/91wHtE+LicS._AC_UY1100_.jpg",
    type: "Silk Anarkali Festive Kurti ",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "1100",
    stockCount: 60,
    deliveryCharge: 25,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://m.media-amazon.com/images/I/812uqSeQucL._SX342_.jpg",
    type: "Women's Mustard Cotton Floral Print",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "750",
    stockCount: 60,
    deliveryCharge: 0,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://m.media-amazon.com/images/I/71qmWQSosyL._AC_UY1100_.jpg",
    type: "Mandarin Collar Printed Kurta",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "1200",
    stockCount: 60,
    deliveryCharge: 30,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://i.pinimg.com/736x/68/3d/c8/683dc8bb0d4282b9af5fe04881a8d6fb.jpg",
    type: "Women Rayon Anarkali Kurti",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "449",
    stockCount: 60,
    deliveryCharge: 0,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://assets0.mirraw.com/images/11749697/image_zoom.jpeg?1691999814",
    type: "Women Straight Kurti",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "965",
    stockCount: 60,
    deliveryCharge: 20,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC08KdaelTposKdVRdOeRThUN1l8Gg8MYulw&usqp=CAU",
    type: "Women's Yellow Cotton A-Line Kurta",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "389",
    stockCount: 60,
    deliveryCharge: 0,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://www.joshindia.com/cdn/shop/products/V3-277-5.jpg?v=1680944502&width=1445",
    type: "Cotton Calf Length Anarkali Kurti",
    colors: ["pink", "orange", "blue", "skyblue", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "1340",
    stockCount: 60,
    deliveryCharge: 35,
    shop: "@2B Boutique",
  },
  //##################################################
  {
    name: "women kurtis",
    src: "https://images.meesho.com/images/products/274493797/wt1oa_512.webp",
    type: "Women Rayon Anarkali Kurti",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "449",
    stockCount: 60,
    deliveryCharge: 0,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/81pK90+Sg2L._AC_UY1100_.jpg",
    type: "Women Straight Kurti",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "965",
    stockCount: 60,
    deliveryCharge: 20,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://assets.ajio.com/medias/sys_master/root/20220315/bsww/6230738daeb26921afd98f24/-473Wx593H-461512199-pink-MODEL.jpg",
    type: "Women's Yellow Cotton A-Line Kurta",
    colors: ["pink", "green", "blue", "orange", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "389",
    stockCount: 60,
    deliveryCharge: 0,
    shop: "@2B Boutique",
  },
  {
    name: "women kurtis",
    src: "https://images.meesho.com/images/products/41026031/kcdag_512.jpg",
    type: "Cotton Calf Length Anarkali Kurti",
    colors: ["pink", "orange", "blue", "skyblue", "red"],
    sizes: [
      { size: "S", value: 10 },
      { size: "M", value: 6 },
      { size: "L", value: 8 },
      { size: "XL", value: 5 },
      { size: "XXL", value: 10 },
      { size: "XXXL", value: 9 },
    ],
    price: "1340",
    stockCount: 60,
    deliveryCharge: 35,
    shop: "@2B Boutique",
  },
];

export const COLORS_WITH_EXCODES = {
  blue: "#0000FF",
  orange: "#FFA500",
  yellow: "#FFD400",
  green: "#A1DFA2",
  deeppink: "#D60178",
  hotpink: "#E76FB3",
  royalblue: "#162453",
  lightblue: "#5A9FD8",
  skyblue: "#9FD9FE",
  lightgreen: "#598061",
  pink: "#F70062",
  brown: "#541513",
  darkbrown: "#3E1213",
  lightbrown: "#BA7D5F",
  grey: "#909090",
  gray: "#636363",
  black: "#000000",
  red: "#FF0000",
  darkblue: "#223BC9",
  palepink: "#E57D90",
};
